version: "3"
# Maintainer Amir Mallaei @ Gmail .com
services:

  app:
    build: .
    image: saho
    container_name: Sahp_app
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./:/code
      - "../db/files/static:/code/static:ro"
      - "../db/files/media:/code/media:rw"
    command: bash Deployment/bashes/createDB.sh
    links:
      - db
    networks:
      dobare_app_net:
        ipv4_address: 192.168.1.100

  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    environment:
       - POSTGRES_DB=saho
       - POSTGRES_USER=saho
       - POSTGRES_PASSWORD=saho1234
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      dobare_app_net:
        ipv4_address: 192.168.1.101

networks:
  dobare_app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
