version: "3"

services:
  app:
    build: .
    image: saho
    container_name: Saho_app
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./:/code
      - "../db/files/static:/code/static:ro"
      - "../db/files/media:/code/media:rw"

    command: bash Deployment/bashes/createDB.sh
    
    environment:
      SAHO_DB_NAME: saho_app_db
      SAHO_POSTGRES_USER: saho_app_usr
      SAHO_POSTGRES_PASSWORD: GarShavadAghlGhomiKharab
      SAHO_POSTGRES_HOST: db
      SAHO_POSTGRES_PORT: 5432

    depends_on:
      - db
    networks:
      saho_app_net: 
        ipv4_address: 192.168.1.100

  db:
    image: postgres:14-alpine
    container_name: saho_app_db
    restart: always
    environment:
      POSTGRES_DB: saho_app_db
      POSTGRES_USER: saho_app_usr
      POSTGRES_PASSWORD: GarShavadAghlGhomiKharab

    volumes:
      - ../db/postgres-data:/var/lib/postgresql/data
    networks:
      saho_app_net: 
        ipv4_address: 192.168.1.101

networks:
  saho_app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
